<?php
declare(strict_types=1);
namespace OCP { interface IRequest {} }
namespace OCA\Recruitment\AppInfo { final class Application { public const APP_ID='adrecruitment'; } }
namespace OCP\AppFramework { class Controller {public function __construct(string $appId,\OCP\IRequest $request){}}final class Http{public const STATUS_FORBIDDEN=403;} }
namespace OCP\AppFramework\Http { final class TemplateResponse {public function __construct(public string $app,public string $template,public array $params=[],public string $renderAs='',public int $status=200){}} }
namespace OCP\AppFramework\Http\Attribute { #[\Attribute(\Attribute::TARGET_METHOD)]final class NoCSRFRequired{}#[\Attribute(\Attribute::TARGET_METHOD)]final class NoAdminRequired{} }
namespace OCA\Recruitment\Exception { final class AccessDeniedException extends \RuntimeException{} }
namespace OCA\Recruitment\Service { final class RecruitmentAccessService{public function __construct(public bool $allowed){}public function requireAnyAccess():void{if(!$this->allowed)throw new \OCA\Recruitment\Exception\AccessDeniedException();}}final class TemporaryAdminAccessService{public function __construct(public bool $manage,public bool $needsGrant){}public function canManage():bool{return $this->manage;}public function currentAdminNeedsGrant():bool{return $this->needsGrant;}} }
namespace {use OCA\Recruitment\Controller\PageController;use OCA\Recruitment\Service\RecruitmentAccessService;use OCA\Recruitment\Service\TemporaryAdminAccessService;$request=new class implements OCP\IRequest{};$response=(new PageController($request,new RecruitmentAccessService(false),new TemporaryAdminAccessService(true,false)))->index();if($response->app!=='adrecruitment'||$response->params['canManageAdminAccess']!==true||$response->params['showMissingAdminGrant']!==false||$response->params['hasRecruitmentAccess']!==false)throw new RuntimeException('DPO ohne Fachrolle erhält keine isolierte Steuerung.');$response=(new PageController($request,new RecruitmentAccessService(false),new TemporaryAdminAccessService(false,true)))->index();if($response->app!=='adrecruitment'||$response->params['showAdminAccessLink']!==false||$response->params['hasRecruitmentAccess']!==false)throw new RuntimeException('Admin ohne DPO erhielt Direktlink oder Fachoberfläche.');$response=(new PageController($request,new RecruitmentAccessService(false),new TemporaryAdminAccessService(true,true)))->index();if($response->params['showAdminAccessLink']!==true)throw new RuntimeException('Admin+DPO erhielt keinen Direktlink.');$response=(new PageController($request,new RecruitmentAccessService(true),new TemporaryAdminAccessService(false,false)))->index();if($response->params['hasRecruitmentAccess']!==true)throw new RuntimeException('Berechtigtes Fachkonto erhielt die Arbeitsoberfläche nicht.');$response=(new PageController($request,new RecruitmentAccessService(false),new TemporaryAdminAccessService(false,false)))->index();if($response->app!=='core'||$response->status!==403)throw new RuntimeException('Gewöhnliches Konto blieb nicht geschützt.');echo "AD Recruitment page controller role projection tests passed\n";}
