<?php
declare(strict_types=1);
namespace Psr\Clock { interface ClockInterface { public function now(): \DateTimeImmutable; } }
namespace Psr\Log { interface LoggerInterface { public function emergency(string|\Stringable $message,array $context=[]):void;public function alert(string|\Stringable $message,array $context=[]):void;public function critical(string|\Stringable $message,array $context=[]):void;public function error(string|\Stringable $message,array $context=[]):void;public function warning(string|\Stringable $message,array $context=[]):void;public function notice(string|\Stringable $message,array $context=[]):void;public function info(string|\Stringable $message,array $context=[]):void;public function debug(string|\Stringable $message,array $context=[]):void;public function log($level,string|\Stringable $message,array $context=[]):void; } }
namespace OCP\AppFramework\Utility { interface ITimeFactory extends \Psr\Clock\ClockInterface { public function getTime(): int; public function getDateTime(string $time='now',?\DateTimeZone $timezone=null):\DateTime; public function withTimeZone(\DateTimeZone $timezone):static; public function getTimeZone(?string $timezone=null):\DateTimeZone; } }
namespace OCA\Recruitment\Repository { interface TemporaryAdminAccessRepositoryInterface { public function replaceActive(string $targetUid,string $grantedBy,\DateTimeImmutable $startsAt,\DateTimeImmutable $endsAt):array; public function revokeActive(string $targetUid,string $revokedBy,\DateTimeImmutable $revokedAt):bool; public function activeFor(string $targetUid,\DateTimeImmutable $at):?array; public function history():array; } }
namespace {
use OCA\Recruitment\Repository\TemporaryAdminAccessRepositoryInterface;
use OCA\Recruitment\Service\TemporaryAdminAccessDeniedException;
use OCA\Recruitment\Service\TemporaryAdminAccessService;
$actor=new class implements OCP\IUser {public function getUID():string{return 'privacy-officer';}};
$session=new class($actor) implements OCP\IUserSession {public function __construct(public ?OCP\IUser $user){}public function getUser():?OCP\IUser{return $this->user;}};
$groups=new class implements OCP\IGroupManager {public array $admins=['admin-target','admin-operator'];public array $privacyOfficers=['privacy-officer'];public function isAdmin(string $uid):bool{return in_array($uid,$this->admins,true);}public function get(string $gid):?OCP\IGroup{if($gid!=='Datenschutzbeauftragte')return null;return new class($this->privacyOfficers) implements OCP\IGroup{public function __construct(private array $members){}public function inGroup(OCP\IUser $user):bool{return in_array($user->getUID(),$this->members,true);}};}};
$clock=new class implements OCP\AppFramework\Utility\ITimeFactory {public function now():DateTimeImmutable{return new DateTimeImmutable('2026-08-25T10:00:00+00:00');}public function getTime():int{return $this->now()->getTimestamp();}public function getDateTime(string $time='now',?DateTimeZone $timezone=null):DateTime{return new DateTime($time,$timezone);}public function withTimeZone(DateTimeZone $timezone):static{return $this;}public function getTimeZone(?string $timezone=null):DateTimeZone{return new DateTimeZone($timezone??'UTC');}};
$repository=new class implements TemporaryAdminAccessRepositoryInterface {public array $rows=[];public int $mutations=0;public bool $failReads=false;public function replaceActive(string $targetUid,string $grantedBy,DateTimeImmutable $startsAt,DateTimeImmutable $endsAt):array{$this->mutations++;foreach($this->rows as &$row)if($row['targetUid']===$targetUid&&$row['revokedAt']===null)$row['revokedAt']=$startsAt;$row=['id'=>count($this->rows)+1,'targetUid'=>$targetUid,'grantedBy'=>$grantedBy,'startsAt'=>$startsAt,'endsAt'=>$endsAt,'revokedAt'=>null,'revokedBy'=>null];$this->rows[]=$row;return $row;}public function revokeActive(string $targetUid,string $revokedBy,DateTimeImmutable $revokedAt):bool{foreach($this->rows as &$row)if($row['targetUid']===$targetUid&&$row['revokedAt']===null){$row['revokedAt']=$revokedAt;$row['revokedBy']=$revokedBy;$this->mutations++;return true;}return false;}public function activeFor(string $targetUid,DateTimeImmutable $at):?array{if($this->failReads)throw new RuntimeException('read failed');foreach(array_reverse($this->rows)as$row)if($row['targetUid']===$targetUid&&$row['revokedAt']===null&&$row['startsAt']<=$at&&$row['endsAt']>$at)return$row;return null;}public function history():array{return array_reverse($this->rows);}};
$logger=new class implements Psr\Log\LoggerInterface {public array $messages=[];public function emergency(string|Stringable $m,array $c=[]):void{}public function alert(string|Stringable $m,array $c=[]):void{}public function critical(string|Stringable $m,array $c=[]):void{}public function error(string|Stringable $m,array $c=[]):void{$this->messages[]=['error',(string)$m,$c];}public function warning(string|Stringable $m,array $c=[]):void{}public function notice(string|Stringable $m,array $c=[]):void{}public function info(string|Stringable $m,array $c=[]):void{$this->messages[]=['info',(string)$m,$c];}public function debug(string|Stringable $m,array $c=[]):void{}public function log($l,string|Stringable $m,array $c=[]):void{}};
$service=new TemporaryAdminAccessService($session,$groups,$repository,$clock,$logger);
if(!$service->canManage()||$service->currentAdminNeedsGrant())throw new RuntimeException('Datenschutzbeauftragte ohne Adminrolle muss Freigaben verwalten können.');
$service->state();
try{$service->activate('admin-target',1441);throw new RuntimeException('Mehr als 24 Stunden akzeptiert.');}catch(InvalidArgumentException){}
try{$service->activate('ordinary',60);throw new RuntimeException('Nicht-Adminziel akzeptiert.');}catch(InvalidArgumentException){}
try{$service->revoke('ordinary');throw new RuntimeException('Nicht-Adminziel widerrufen.');}catch(InvalidArgumentException){}
if($repository->mutations!==0)throw new RuntimeException('Ungültige Eingaben dürfen nichts verändern.');
$grant=$service->activate('admin-target',1440);if($grant['grantedBy']!=='privacy-officer')throw new RuntimeException('Audit-Akteur ist falsch.');if(!$service->hasActiveGrant('admin-target')||$service->hasActiveGrant('ordinary'))throw new RuntimeException('Freigabe ist nicht UID- und Admin-genau.');
$groups->admins=['admin-operator'];if($service->hasActiveGrant('admin-target'))throw new RuntimeException('Entzogener Adminstatus muss Freigabe beenden.');$groups->admins=['admin-target','admin-operator'];$groups->privacyOfficers=[];$before=$repository->mutations;try{$service->revoke('admin-target');throw new RuntimeException('Verlorene Datenschutzrolle durfte widerrufen.');}catch(TemporaryAdminAccessDeniedException){}if($repository->mutations!==$before)throw new RuntimeException('Abgewiesener Widerruf mutierte.');
$groups->privacyOfficers=['privacy-officer'];if(!$service->revoke('admin-target')||$repository->rows[0]['revokedBy']!=='privacy-officer')throw new RuntimeException('Widerrufsaudit muss die Datenschutzrolle erfassen.');$groups->privacyOfficers=[];
$session->user=new class implements OCP\IUser{public function getUID():string{return 'admin-operator';}};if($service->canManage()||!$service->currentAdminNeedsGrant())throw new RuntimeException('Adminhinweisprojektion falsch.');foreach(['state','activate','revoke']as$method){$before=$repository->mutations;try{if($method==='state')$service->state();elseif($method==='activate')$service->activate('admin-target',60);else$service->revoke('admin-target');throw new RuntimeException('Native Administration ohne Datenschutzrolle zugelassen.');}catch(TemporaryAdminAccessDeniedException){}if($repository->mutations!==$before)throw new RuntimeException('Verweigerte Aktion mutierte.');}
$session->user=new class implements OCP\IUser{public function getUID():string{return 'ordinary';}};if($service->canManage()||$service->currentAdminNeedsGrant())throw new RuntimeException('Gewöhnliches Konto erhielt Rollenprojektion.');try{$service->state();throw new RuntimeException('Gewöhnliches Konto las Historie.');}catch(TemporaryAdminAccessDeniedException){}
$repository->failReads=true;if($service->hasActiveGrant('admin-target'))throw new RuntimeException('Repositoryfehler muss geschlossen verweigern.');
echo "AD Recruitment temporary admin access service tests passed\n";
}
