<?php

declare(strict_types=1);

return ['routes' => [
    ['name' => 'page#index', 'url' => '/', 'verb' => 'GET'],
    ['name' => 'api#bootstrap', 'url' => '/api/bootstrap', 'verb' => 'GET'],
    ['name' => 'api#inbox', 'url' => '/api/inbox', 'verb' => 'GET'],
    ['name' => 'api#inboxMessage', 'url' => '/api/inbox/{id}', 'verb' => 'GET'],
    ['name' => 'api#applicationMessages', 'url' => '/api/applications/{id}/messages', 'verb' => 'GET'],
    ['name' => 'api#assignInboxMessage', 'url' => '/api/inbox/{id}/assign', 'verb' => 'POST'],
    ['name' => 'api#ignoreInboxMessage', 'url' => '/api/inbox/{id}/ignore', 'verb' => 'POST'],
    ['name' => 'api#attachmentDocument', 'url' => '/api/attachments/{id}/document', 'verb' => 'GET'],
    ['name' => 'api#attachmentComments', 'url' => '/api/attachments/{id}/comments', 'verb' => 'GET'],
    ['name' => 'api#createAttachmentComment', 'url' => '/api/attachments/{id}/comments', 'verb' => 'POST'],
    ['name' => 'api#attachmentFieldContext', 'url' => '/api/attachments/{id}/field-context/{targetField}', 'verb' => 'GET'],
    ['name' => 'api#createAttachmentFieldLink', 'url' => '/api/attachments/{id}/field-links', 'verb' => 'POST'],
    ['name' => 'api#applicationDetail', 'url' => '/api/applications/{id}', 'verb' => 'GET'],
    ['name' => 'api#templateDetail', 'url' => '/api/templates/{id}', 'verb' => 'GET'],
    ['name' => 'api#createJob', 'url' => '/api/jobs', 'verb' => 'POST'],
    ['name' => 'api#jobResponsibilityUsers', 'url' => '/api/job-responsibility-users', 'verb' => 'GET'],
    ['name' => 'api#createBasisQualificationRun', 'url' => '/api/basis-qualifications', 'verb' => 'POST'],
    ['name' => 'api#setJobBasisQualificationRequired', 'url' => '/api/jobs/{id}/basis-qualification', 'verb' => 'PUT'],
    ['name' => 'api#basisQualificationAssignments', 'url' => '/api/applications/{id}/basis-qualifications', 'verb' => 'GET'],
    ['name' => 'api#assignBasisQualification', 'url' => '/api/applications/{id}/basis-qualification', 'verb' => 'POST'],
    ['name' => 'api#recordBasisQualificationResult', 'url' => '/api/basis-qualification-assignments/{id}/result', 'verb' => 'PUT'],
    ['name' => 'api#createPerson', 'url' => '/api/people', 'verb' => 'POST'],
    ['name' => 'api#createApplication', 'url' => '/api/applications', 'verb' => 'POST'],
    ['name' => 'api#createTemplate', 'url' => '/api/templates', 'verb' => 'POST'],
    ['name' => 'api#createQuestion', 'url' => '/api/templates/{templateId}/questions', 'verb' => 'POST'],
    ['name' => 'api#updateQuestion', 'url' => '/api/questions/{id}', 'verb' => 'PUT'],
    ['name' => 'api#createBubble', 'url' => '/api/questions/{questionId}/bubbles', 'verb' => 'POST'],
    ['name' => 'api#createInterview', 'url' => '/api/applications/{applicationId}/interviews', 'verb' => 'POST'],
    ['name' => 'api#saveInterviewDraft', 'url' => '/api/interviews/{id}/draft', 'verb' => 'PUT'],
    ['name' => 'api#completeInterview', 'url' => '/api/interviews/{id}/complete', 'verb' => 'POST'],
    ['name' => 'api#transitionStatus', 'url' => '/api/applications/{id}/status', 'verb' => 'POST'],
    ['name' => 'api#mailConfiguration', 'url' => '/api/mail/configuration', 'verb' => 'GET'],
    ['name' => 'api#createMailTemplate', 'url' => '/api/mail/templates', 'verb' => 'POST'],
    ['name' => 'api#reviseMailTemplate', 'url' => '/api/mail/templates/{id}', 'verb' => 'PUT'],
    ['name' => 'api#saveStatusMailRule', 'url' => '/api/mail/rules', 'verb' => 'PUT'],
    ['name' => 'api#createMailTextBlock', 'url' => '/api/mail/text-blocks', 'verb' => 'POST'],
    ['name' => 'api#applicationMailDrafts', 'url' => '/api/applications/{id}/mail-drafts', 'verb' => 'GET'],
    ['name' => 'api#saveMailDraft', 'url' => '/api/mail-drafts/{id}', 'verb' => 'PUT'],
    ['name' => 'api#approveMailDraft', 'url' => '/api/mail-drafts/{id}/approve', 'verb' => 'POST'],
    ['name' => 'api#cancelMailDraft', 'url' => '/api/mail-drafts/{id}/cancel', 'verb' => 'POST'],
    ['name' => 'api#saveMailSettings', 'url' => '/api/mail/settings', 'verb' => 'PUT'],
    ['name' => 'api#hiringData', 'url' => '/api/applications/{id}/hiring-data', 'verb' => 'GET'],
    ['name' => 'api#saveHiringData', 'url' => '/api/applications/{id}/hiring-data', 'verb' => 'PUT'],
    ['name' => 'api#savePayrollData', 'url' => '/api/applications/{id}/payroll-data', 'verb' => 'PUT'],
    ['name' => 'api#setFirstGuideAccess', 'url' => '/api/applications/{id}/first-guide-access', 'verb' => 'PUT'],
    ['name' => 'api#saveRepresentatives', 'url' => '/api/permissions/representatives', 'verb' => 'PUT'],
    ['name' => 'api#saveFirstGuideGroup', 'url' => '/api/permissions/first-guide-group', 'verb' => 'PUT'],
    ['name' => 'api#candidatePool', 'url' => '/api/candidate-pool', 'verb' => 'GET'],
    ['name' => 'api#requestCandidatePool', 'url' => '/api/applications/{id}/candidate-pool/request', 'verb' => 'POST'],
    ['name' => 'api#grantCandidatePoolConsent', 'url' => '/api/candidate-pool/{id}/consent', 'verb' => 'POST'],
    ['name' => 'api#withdrawCandidatePoolConsent', 'url' => '/api/candidate-pool/{id}/withdraw', 'verb' => 'POST'],
    ['name' => 'api#saveCandidatePoolSettings', 'url' => '/api/candidate-pool/settings', 'verb' => 'PUT'],
    ['name' => 'api#saveResumeExtractionSettings', 'url' => '/api/resume-extraction/settings', 'verb' => 'PUT'],
]];
